# Generated by Django 4.0.4 on 2023-08-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='price',
            field=models.IntegerField(),
        ),
    ]
