# Generated by Django 4.0.4 on 2023-08-22 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0003_alter_user_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='tbl_User',
        ),
    ]
